stages:
  - build
  - docker
  - deploy

build:
  stage: build
  image: maven:3.6.0-jdk-11
  script:
    - mvn package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

docker:
  stage: docker
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.1-dind
  image: docker:19.03.1
  script:
    - docker build --pull -t "donatien26/appli-opensource:$CI_COMMIT_REF_SLUG" .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker push "donatien26/appli-opensource:$CI_COMMIT_REF_SLUG"

deploy review on kub:
  stage: deploy
  image:
    name: thisiskj/kubectl-envsubst
    entrypoint: ["/bin/sh", "-c"]
  script:
    - envsubst < .ci/ci.yaml
    - envsubst < .ci/ci.yaml | kubectl --token $KUB_TOKEN --server $KUB_SERVER --namespace $KUB_NAMESPACE --insecure-skip-tls-verify=true replace --force -f -
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://appli-opensource-${CI_COMMIT_REF_SLUG}.dev.insee.io
    on_stop: stop_review on kub

stop_review on kub:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  image:
    name: thisiskj/kubectl-envsubst
    entrypoint: ["/bin/sh", "-c"]
  script:
    - envsubst < .ci/ci.yaml | kubectl --token $KUB_TOKEN --server $KUB_SERVER --namespace $KUB_NAMESPACE --insecure-skip-tls-verify=true delete -f -
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
