---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-demo-${CI_COMMIT_REF_SLUG}
spec:
  selector:
    matchLabels:
      app: open-demo-${CI_COMMIT_REF_SLUG}
  template:
    metadata:
      labels:
        app: open-demo-${CI_COMMIT_REF_SLUG}
    spec:
      containers:
        - name: open-demo-${CI_COMMIT_REF_SLUG}
          image: "donatien26/appli-opensource:${CI_COMMIT_REF_SLUG}"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: open-demo-${CI_COMMIT_REF_SLUG}
spec:
  selector:
    app: open-demo-${CI_COMMIT_REF_SLUG}
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-demo-${CI_COMMIT_REF_SLUG}
  labels:
    name: open-demo-${CI_COMMIT_REF_SLUG}
  annotation:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - appli-opensource-${CI_COMMIT_REF_SLUG}.dev.insee.io
  rules:
    - host: appli-opensource-${CI_COMMIT_REF_SLUG}.dev.insee.io
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: open-demo-${CI_COMMIT_REF_SLUG}
                port:
                  number: 8080
